export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';
export const OPEN_ADD_EMPLOYEE_FORM = 'OPEN_ADD_EMPLOYEE_FORM';
export const OPEN_UPDATE_EMPLOYEE_FORM = 'OPEN_UPDATE_EMPLOYEE_FORM';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

